apiVersion: apps/v1
kind: Deployment
metadata:
  generation: 1
  labels:
    app: kafka-certification
  name: kafka-certification
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: kafka-certification
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: kafka-certification
    spec:
      containers:
      - image: ubuntu:24.04
        imagePullPolicy: Always
        name: ubuntu
        command: ["/bin/bash", "-c", "/scripts/setup.sh && sleep infinity"]
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        envFrom:
        - secretRef:
            name: kafka-certification-aws-creds
        volumeMounts:
        - name: setup
          mountPath: /scripts/
        - name: storage
          mountPath: /storage
          readOnly: false
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: kafka-certification
      automountServiceAccountToken: true
      terminationGracePeriodSeconds: 30
      volumes:
      - name: setup
        configMap:
          name: kafka-certification-cm
          items:
          - key: setup
            path: setup.sh
            mode: 0755
      - name: storage
        persistentVolumeClaim:
          claimName: data-kafka-certification
