---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-kafka-certification
spec:
  storageClassName: longhorn-crypto-global
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
