apiVersion: v1
kind: ServiceAccount
metadata:
  name: kafka-certification

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kafka-certification
rules:
- apiGroups: [""] 
  verbs: ["get", "list", "watch", "delete", "patch", "create", "update", "deletecollection"]
  resources: ["*"]
- apiGroups: ["apps"] 
  verbs: ["get", "list", "watch", "delete", "patch", "create", "update", "deletecollection"]
  resources: ["*"]
- apiGroups:
  - "rbac.authorization.k8s.io"
  resources: ["*"]
  verbs:
    - get
    - list
    - watch
    - create
    - update
    - delete
    - patch
- apiGroups:
    - networking.k8s.io
  resources: ["*"]
  verbs:
    - get
    - list
    - watch
    - create
    - update
    - delete
    - patch
- apiGroups:
    - storage.k8s.io
  resources: ["*"]
  verbs:
    - get
    - list
    - watch
    - create
    - update
    - delete
    - patch
- apiGroups:
  - "policy"
  - "policy/v1beta1"
  resources: ["*"]
  verbs:
    - get
    - list
    - watch
    - create
    - update
    - delete
    - patch
- apiGroups:
  - "batch"
  resources: ["*"]
  verbs:
    - get
    - list
    - watch
    - create
    - update
    - delete
    - patch
- apiGroups:
  - "coordination.k8s.io"
  resources: ["*"]
  verbs:
    - get
    - list
    - watch
    - create
    - update
    - delete
    - patch
- apiGroups:
  - "directpv.min.io"
  resources: ["*"]
  verbs:
    - get
    - list
    - watch
    - create
    - update
    - delete
    - patch
- apiGroups:
  - "snapshot.storage.k8s.io"
  resources: ["*"]
  verbs:
    - get
    - list
    - watch
    - create
    - update
    - delete
    - patch
- apiGroups:
  - "policy"
  resources: ["*"]
  verbs:
    - get
    - list
    - watch
    - create
    - update
    - delete
    - patch
    - use
- apiGroups:
  - "apiextensions.k8s.io"
  resources: ["*"]
  verbs:
    - get
    - list
    - watch
    - create
    - update
    - delete
    - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kafka-certification
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kafka-certification
subjects:
- kind: ServiceAccount
  name: kafka-certification
  namespace: dev-tutug
